homepage:
    path: /
    defaults: { _controller: MylkBlogBundle:Default:index }
    
search:
    path: /search
    defaults: { _controller: MylkBlogBundle:Default:search }

post:
    path: /post/{postid}
    defaults: { _controller: MylkBlogBundle:Default:postView }
    
category:
    path: /category/{categoryid}
    defaults: { _controller: MylkBlogBundle:Default:categoryView }
    
tag:
    path: /tag/{tagid}
    defaults: { _controller: MylkBlogBundle:Default:tagView }
    
archive:
    path: /{year}/{month}
    defaults: { _controller: MylkBlogBundle:Default:archiveView }
    requirements:
        year: \d+
        month: \d+
    
rss:
    path: /rss
    defaults: { _controller: MylkBlogBundle:Default:rss }
    
comment_submit:
    path: /comment/submit
    defaults: { _controller: MylkBlogBundle:Default:commentSubmit }



admin_homepage:
    path: /admin
    defaults: { _controller: MylkBlogBundle:Admin:index }

admin_login:
    path: /admin/login
    defaults: { _controller: MylkBlogBundle:Admin:login }

admin_login_check:
    path: /admin/login/check
    defaults: { _controller: MylkBlogBundle:Admin:loginCheck }

admin_logout:
    path: /admin/logout
    defaults: { _controller: MylkBlogBundle:Admin:logout }

admin_post_list:
    path: /admin/post/list
    defaults: { _controller: MylkBlogBundle:Admin:postList }
    
admin_post_new:
    path: /admin/post/new
    defaults: { _controller: MylkBlogBundle:Admin:postNew }
    
admin_post_edit:
    path: /admin/post/edit/{postid}
    defaults: { _controller: MylkBlogBundle:Admin:postEdit }
    requirements:
        postid: \d+



gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"