security:
    encoders:
        Mylk\Bundle\BlogBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        admins:
            entity: { class: MylkBlogBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            anonymous:  ~
            provider:   ~
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path:  admin_homepage
                csrf_provider: security.csrf.token_manager
            logout:
                path:   admin_logout
                target: admin_login

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
