parameters:
#    mylk_blog.example.class: Mylk\Bundle\BlogBundle\Example

services:
#    mylk_blog.example:
#        class: %mylk_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
