services:
    mylk_blog.rss_generator:
        class: Mylk\Bundle\BlogBundle\Service\RssFeedGeneratorService
        calls: [ [setupDependencies, [%rss_feed_title%, %rss_feed_url_homepage%, %rss_feed_url_feed%, %rss_feed_description%]] ]

    mylk_blog.menu_generator:
        class: Mylk\Bundle\BlogBundle\Service\MenuGeneratorService

    login_listener:
        class: Mylk\Bundle\BlogBundle\EventListener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLoginSuccess }
        arguments: ["@doctrine.orm.entity_manager"]

    comment_listener:
        class: Mylk\Bundle\BlogBundle\EventListener\CommentListener
        tags:
            - { name: kernel.event_listener, event: mylk_blogbundle.comment_added, method: onComment }
        arguments: ["@mailer", "@router", "%mailer_user%", "%comment_notified_emails%"]
